### ISSUE TITLE
DSS Payment Demographic Data

### ISSUE THREAD

**Issue by Louis-DJPR** [djpr-data/djpr-import-r#1]

**Comment by beaudjpr** [comment]
unable to use `url_updates` script to find most recent version of code as the url for each download has inconsistent naming:

Dec-21 = https://data.gov.au/data/dataset/dss-payment-demographic-data/resource/65515027-eb42-4257-9b32-6bfec21e00e8
Sept-21 = https://data.gov.au/data/dataset/dss-payment-demographic-data/resource/80cc89a3-3208-4e0d-9745-598f7a882e28
